version: "2"
run:
  tests: false
  allow-parallel-runners: true
linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - dupword
    - durationcheck
    - err113
    - errchkjson
    - errname
    - errorlint
    - forcetypeassert
    - gocritic
    - godot
    - goprintffuncname
    - gosec
    - importas
    - ireturn
    - maintidx
    - mirror
    - misspell
    - nakedret
    - nilnil
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - reassign
    - revive
    - staticcheck
    - unconvert
    - unparam
    - usestdlibvars
    - usetesting
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
  settings:
    varnamelen:
      max-distance: 10
      ignore-decls:
        - w http.ResponseWriter
        - r *http.Request
        - i int
        - n int
        - p []byte
        - mu sync.Mutex
        - wg sync.WaitGroup
        - h Host
        - h os.Host
        - h *api.Host
        - ok bool
        - s string
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - .*\.gen\.go
      - examples/*
      - test/*
      - logo.go
      - logo_windows.go
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - .*\.gen\.go
      - examples/*
      - test/*
      - logo.go
      - logo_windows.go
