run:
  timeout: 8m

  tests: false
  allow-parallel-runners: true
  build-tags:
    - 'testing'

issues:
  exclude-dirs-use-default: false
  exclude-files:
    - ".*\\.gen\\.go"
    - examples/*
    - test/*
    - logo.go
    - logo_windows.go
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    # enabled by default
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    # additional
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - dupword
    - durationcheck
    - err113
    - errchkjson
    - errname
    - errorlint
    - forcetypeassert
    - gci
    - gocritic
    - godot
    - gofmt
    - gofumpt
    - goimports
    - goprintffuncname
    - gosec
    - importas
    - ireturn
    - maintidx
    - mirror
    - misspell
    - nakedret
    - nilnil
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - reassign
    - revive
    - stylecheck
    - tenv
    - unconvert
    - unparam
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck

linters-settings:
  varnamelen:
    max-distance: 10
    ignore-decls:
      - w http.ResponseWriter
      - r *http.Request
      - i int
      - n int
      - p []byte
      - mu sync.Mutex
      - wg sync.WaitGroup
      - h Host
      - h os.Host
      - h *api.Host
      - ok bool
      - s string

