#
# GoRelease instructions for local builds
#
project_name: launchpad
version: 2
builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -X github.com/Mirantis/mcc/version.Environment=development
      - -X github.com/Mirantis/mcc/version.GitCommit={{ .FullCommit }}
      - -X github.com/Mirantis/mcc/version.Version={{ .Version }}
      # if segment analytics is to be active, set an env variable for the token
      - -X github.com/Mirantis/mcc/pkg/analytics.SegmentToken={{ .Env.SEGMENT_TOKEN }}
    binary: "{{ .ProjectName }}"
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - amd64
      - arm64
