apiVersion: "launchpad.mirantis.com/v1beta2"
kind: UCP
spec:
  hosts:
    - address: "127.0.0.1"
      ssh:
        port: 9022
        user: "root"
      role: "manager"
    - address: "127.0.0.1"
      ssh:
        port: 9023
        user: "root"
      role: "worker"
  ucp:
    installFlags:
      - --admin-username=admin
      - --admin-password=orcaorcaorca
      - --default-node-orchestrator=kubernetes
