apiVersion: "launchpad.mirantis.com/mke/v1.1"
kind: mke
spec:
  hosts:
    - address: "127.0.0.1"
      ssh:
        port: 9022
        user: "root"
      role: "manager"
    - address: "127.0.0.1"
      ssh:
        port: 9023
        user: "root"
      role: "worker"
  mke:
    version: 3.3.0-rc4
    # Use custom image repo, remember to set the REGISTRY_USERNAME & REGISTRY_PASSWORD envs
    imageRepo: docker.io/dockereng
    installFlags:
      - --admin-username=admin
      - --admin-password=orcaorcaorca
      - --default-node-orchestrator=kubernetes
