apiVersion: "launchpad.mirantis.com/v1beta3"
kind: UCP
spec:
  hosts:
    - address: "127.0.0.1"
      ssh:
        port: 9022
        user: "root"
      role: "manager"
      engineConfig: &linuxEngineConfig
        debug: true
        log-opts:
          max-size: 10m
          max-file: "3"
    - address: "127.0.0.1"
      ssh:
        port: 9023
        user: "root"
      role: "worker"
      engineConfig: *linuxEngineConfig
  ucp:
    installFlags:
      - --admin-username=admin
      - --admin-password=orcaorcaorca
      - --default-node-orchestrator=kubernetes
