apiVersion: "launchpad.mirantis.com/v1"
kind: DockerEnterprise
spec:
  hosts:
    - address: "147.75.55.123"
      ssh:
        port: 22
        user: "root"
      role: "manager"
      engineConfig: &linuxEngineConfig
        debug: true
        log-opts:
          max-size: 10m
          max-file: "3"
      hooks:
        apply:
          before:
            - ls -al
            - echo hello > foo.txt
          after:
            - ls -al foo.txt
            - cat foo.txt
    # - address: "147.75.87.85"
    # ssh:
    #   port: 22
    #   user: "root"
    # role: "worker"
    # engineConfig: *linuxEngineConfig
  ucp:
    installFlags:
      - --admin-username=admin
      - --admin-password=orcaorcaorca
      - --default-node-orchestrator=kubernetes
