name: Go lint
on:
  pull_request:
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '.golangci.yml'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Configure Git SSH keys
        uses: shaunco/ssh-agent@git-repo-mapping
        with:
          ssh-private-key: |
            ${{ secrets.MSR_OPERATOR_SSH_PRIVATE_KEY }}
          repo-mappings: |
            github.com/Mirantis/msr-operator

      - name: Check go.mod/go.sum to be consistent
        run: go mod tidy -v && git diff --exit-code

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          skip-cache: true
          only-new-issues: false
          args: --verbose
