name: Release binaries to Mirantis/Launchpad

on:
    push:
        tags:
            - v*
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Configure Git SSH keys
              uses: shaunco/ssh-agent@git-repo-mapping
              with:
                ssh-private-key: |
                  ${{ secrets.MSR_OPERATOR_SSH_PRIVATE_KEY }}
                repo-mappings: |
                  github.com/Mirantis/msr-operator
            - name: Run release script
              env:
                TAG_NAME: ${{ github.ref_name }}
                SM_API_KEY: ${{ secrets.SM_API_KEY }}
                SM_CLIENT_CERT_PASSWORD: ${{ secrets.SM_CLIENT_CERT_PASSWORD }}
              run: |
                echo "${{ secrets.SM_CLIENT_PKC12_CERT }}" > secret.txt
                echo "SM_CLIENT_CERT_FILE=$(pwd)/secret.txt" >> $GITHUB_ENV
                make release
