name: Release binaries to Mirantis/Launchpad

on:
    push:
        tags:
            - test*
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Set up ENVs
              run: |
                echo -n "${{ secrets.SM_CLIENT_PKC12_CERT }}" > sign_cert.p12
                echo "SM_CLIENT_CERT_FILE_PATH=$(pwd)/sign_cert.p12" >> $GITHUB_ENV
            - name: Run release script
              env:
                TAG_NAME: ${{ github.ref_name }}
                SM_API_KEY: ${{ secrets.SM_API_KEY }}
                SM_CLIENT_CERT_PASSWORD: ${{ secrets.SM_CLIENT_CERT_PASSWORD }}
                SM_CLIENT_CERT_FILE: ${{ env.SM_CLIENT_CERT_FILE_PATH }}
              run: |
                ls -la
                make release
