# Release workflow for Launchpad
# Triggered on tags (e.g., v1.5.16).

name: Release
permissions:
  contents: read  # Top-level: Restricts all jobs by default
  packages: write  # Required for uploading artifacts

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build Release Binaries
    runs-on: ubuntu-latest
    env:
      GOTOOLCHAIN: auto

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Build binaries
        run: |
          mkdir -p dist
          VERSION=${{ github.ref_name }}
          platforms=("linux/amd64" "linux/arm64" "windows/amd64" "windows/arm64" "darwin/amd64" "darwin/arm64" "freebsd/amd64" "freebsd/arm64")
          for platform in "${platforms[@]}"; do
            GOOS=${platform%/*}
            GOARCH=${platform#*/}
            output_name="dist/launchpad_${GOOS}_${GOARCH}_${VERSION#v}"
            if [ "$GOOS" = "windows" ]; then
              output_name+=".exe"
            fi
            echo "Building $output_name"
            GOOS=$GOOS GOARCH=$GOARCH go build -ldflags "-X github.com/Mirantis/launchpad/version.Version=${VERSION#v} -X github.com/Mirantis/launchpad/version.GitCommit=$GITHUB_SHA" -o "$output_name" ./main.go
          done
      - name: Generate checksums
        run: |
          cd dist
          sha256sum launchpad_* > checksums.sha256

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: launchpad-release-binaries
          path: dist/

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Download binaries
        uses: actions/download-artifact@v7
        with:
          name: launchpad-release-binaries
          path: dist/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          generate_release_notes: true
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # TODO: Add Digicert signing here.
      # TODO: Push signed artifacts to S3 here.
