name: Release binaries to Mirantis/Launchpad

on:
    push:
        tags:
            - v*
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Run release script
              env:
                TAG_NAME: ${{ github.ref_name }}
                SM_API_KEY: ${{ secrets.SM_API_KEY }}
                SM_CLIENT_CERT_FILE: ${{ secrets.SM_CLIENT_CERT_FILE }}
                SM_CLIENT_CERT_PASSWORD: ${{ secrets.SM_CLIENT_CERT_PASSWORD }}
              run: make release
