name: Smoke Small Test

on: 
  pull_request:
    paths:
      - '**.go'
      - go.mod
      - go.sum
      - Makefile

jobs:
    smoke-small:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
            - name: Run small Smoke Tests
              env: 
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              run: |
                make smoke-small
                make clean-launchpad-chart

